# Extensions and skins are bundled by Canasta unless noted otherwise.
extensions:
  - AbuseFilter
  - ApprovedRevs
  - ConfirmEdit
  - ConfirmEdit/QuestyCaptcha
  - Moderation
  - OATHAuth
  - PageForms
  - ParserFunctions
  - SemanticMediaWiki
  - SpamBlacklist
  - TitleBlacklist
  - VisualEditor
skins:
  - Vector
